from node:22-alpine
workdir /app
COPY package.json package-lock.json ./

RUN --mount=type=cache,target=/root/.npm \
  if [ -f package-lock.json ]; then \
    npm ci --no-audit --no-fund; \
  fi
  
ARG NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
COPY . .
ENV NODE_ENV=production
RUN npm run build
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=4000
ENV HOSTNAME="0.0.0.0"

COPY public ./public

EXPOSE 4000

CMD ["npm", "start"]